### ISSUE TITLE
[meta] Checklist before first publication

### ISSUE THREAD

**Issue by moedn** [OPEN-NEXT/LOSH-Reporter#10]
@hoijui quickly went through the current version → looks neat! Here are a few things I discovered; let's use this issue as a ToDo list and create dedicated issues on the individual items if needed

- [ ] error when executing `report.ipynb` see #11 @hoijui 
- [x] add wikifactory data to project-count statistics (`In 2`and `In 3` and possibly also other ones) @hoijui 
- [x] complete CPC section @hoijui 
- [x] complete platform-specific sections @hoijui 
  - [x] OSHWA
  - [x] WIF
- [x] add link to the newsletter @moedn 
- [x] add more descriptions (intro/outro) @moedn 
- [x] fill section of flagship OSH projects @moedn
